### ISSUE TITLE
墙内似乎显示不了结果呀

### ISSUE THREAD

**Issue by ileadall42** [BadTudou/Alfred-workflow-Jiumo#2]
墙内似乎显示不了结果呀。

**Comment by BadTudou** [comment]
无须翻墙，如果有问题，可能是未对错误进行处理：比如搜索的关键字小于4个之类。

已根据网友反馈做了一修改，你可以尝试一下新的版本。

如果仍有问题，请提供发生故障的详细信息：如Alfred版本号、错误信息。

你可以在Jiumo-search的Workflow右上角，点击"虫子"图标，开启调试模式。

**Comment by ileadall42** [comment]
![image](https://user-images.githubusercontent.com/27263086/37756941-3440dfa8-2de6-11e8-91de-7554ec4097de.png)
![image](https://user-images.githubusercontent.com/27263086/37756958-420122ec-2de6-11e8-87b9-7c77105affad.png)
![image](https://user-images.githubusercontent.com/27263086/37756966-4d3a9b0c-2de6-11e8-9807-cfd6ebbb085f.png)
三张小图，我才知道原来阿福也有调试。

**Comment by BadTudou** [comment]
已升级到v0.1.2，v0.1.1中修复了你所提及到的问题，v0.1.2增加了错误提示。

你可以安装最新版尝试一下。

**Comment by ileadall42** [comment]
可以了，谢谢作者
